name: Update Event Data

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:         # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write       # Needed for pushing changes
    
    env:
      USER_AGENT: ${{ secrets.USER_AGENT }}
      WIKI_PAGE_URL: ${{ secrets.WIKI_PAGE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create data directory
        run: mkdir -p docs/data
          
      - name: Update event data
        run: python update_data.py
        
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/data/updates.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update event data" && git push)